<?php

return [
    [
        'name'    => 'bootstrap-navbar-sticky',
        'path'    => 'web.widgets.bootstrap-navbar-sticky',
        'group'   => 'header',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'bootstrap-carousel-fade',
        'path'    => 'web.widgets.bootstrap-carousel-fade',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 0,
    ],
    [
        'name'    => 'bootstrap-carousel-slide',
        'path'    => 'web.widgets.bootstrap-carousel-slide',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'introduction',
        'path'    => 'web.widgets.introduction',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'faq-accordion',
        'path'    => 'web.widgets.faq-accordion',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'featured-gallery',
        'path'    => 'web.widgets.featured-gallery',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'featured-images-gallery',
        'path'    => 'web.widgets.featured-images-gallery',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'featured-articles',
        'path'    => 'web.widgets.featured-articles',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'articles',
        'path'    => 'web.widgets.articles',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'article',
        'path'    => 'web.widgets.article',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'owl-customers',
        'path'    => 'web.widgets.owl-customers',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'first_parallax',
        'path'    => 'web.widgets.first_parallax',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'second_parallax',
        'path'    => 'web.widgets.second_parallax',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'third_parallax',
        'path'    => 'web.widgets.third_parallax',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'scroll-back-to-top',
        'path'    => 'web.widgets.scroll-back-to-top',
        'group'   => 'master',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'preloader',
        'path'    => 'web.widgets.preloader',
        'group'   => 'master',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'featured-products',
        'path'    => 'web.widgets.featured-products',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'products',
        'path'    => 'web.widgets.products',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'product',
        'path'    => 'web.widgets.product',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'featured-services',
        'path'    => 'web.widgets.featured-services',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'services',
        'path'    => 'web.widgets.services',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'service',
        'path'    => 'web.widgets.service',
        'group'   => 'single',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'popup',
        'path'    => 'web.widgets.popup',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'user-register',
        'path'    => 'web.widgets.user-register',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'user-login',
        'path'    => 'web.widgets.user-login',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'user-forget-password',
        'path'    => 'web.widgets.user-forget-password',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'user-profile',
        'path'    => 'web.widgets.user-profile',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => '404',
        'path'    => 'web.widgets.404',
        'group'   => 'errors',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => '500',
        'path'    => 'web.widgets.500',
        'group'   => 'errors',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'footer',
        'path'    => 'web.widgets.footer',
        'group'   => 'footer',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'googlemap',
        'path'    => 'web.widgets.googlemap',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
    [
        'name'    => 'contact_form',
        'path'    => 'web.widgets.contact_form',
        'group'   => 'home',
        'active'  => 0,
        'approve' => 1,
    ],
];

